version: '3.1'

services:
  db:
    container_name: brigid-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    container_name: brigid-adminer
    image: adminer:4
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
